config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :products do
    resources :reviews 
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
        can :create, :reviews
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product)
  
  scope :most_recent, -> { order(created_at: :desc).limit(3) }

  scope :search, -> (name_parameter) { where("LOWER(name) like ?", "%#{name_parameter.downcase}%") }

  scope :most_reviewed, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content, length: { in: 50..250 }
  validates :rating, numericality: { only_integer: true, less_than: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({roles: [] },:admin, :email, :name, :password, :password_confirmation)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @products = Product.all
    @new_products = Product.most_recent
    @reviewed_product = Product.most_reviewed
    @user = current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource :except => :create
  def index
    @products = Product.order(:name).page(params[:page])
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to product_path(@product)
      flash[:notice] = "Product successfully added!"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(products_params)
      redirect_to product_path(@product)
      flash[:notice] = "Product successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  private
    def products_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource :except => [:create, :new]
  def new 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    redirect_to product_path(@product)
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy 
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
end

private
  def review_params
    params.require(:review).permit(:author, :content, :rating)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to products_path
  #   else
  #     redirect_to root_path
  #   end
  # end

  private
    def user_params
      params.require(:user).permit(:admin, :email, :password, :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/views/home/index.html.erb
<h1> Welcome to Mario's Specialty Foods Store! </h1>

<% if !current_user %>
  <%= link_to "Sign Up!", new_user_registration_path %>
  <br>
  <%= link_to "Sign In!", new_user_session_path%>
  <br>
<% end %>
<br>
<div class="home">
  <h2><%= link_to "Check out our Inventory!", products_path %></h2>
  <hr>
  <% if @new_products.any?%>
    <h2> Check out what's new: </h2>
    <ul>
      <% @new_products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  <% end %>
  <% if @reviewed_product.any? %>
    <h3> Check out our <em>Most Reviewed Product: </em></h3>
    <ul>
      <li><%= link_to @reviewed_product.first.name, product_path(@reviewed_product.first)  %></li>
    </ul>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_area :content, placeholder: "50-250 characters please" %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: 1..5 %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marios Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://fonts.googleapis.com/css2?family=Oswald&family=Pacifico&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar">
        <a class="navbar-brand" href="/users/sign_in">Mario's</a>
        <div class="nav-bar-links">
          <a class="nav-item nav-link" href="/users/sign_in">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="/products">Inventory</a>
          <a class=" nav-item nav-link" href="/users/sign_out" data-method="delete" value="<%= destroy_user_session_path%>">Sign Out</a>
        </div>
      </nav>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>
<hr>
<p>Search for a product:</p>
<%= form_tag(products_path, method: :get) do %>
  <%= text_field_tag(:name_search, params[:name_search]) %>
  <%= submit_tag ("Search") %>
<% end %>
<br>
<br>

<% if @search_results %>
  <% if @search_results.any? %>
    <h4>Here are your products:</h4>
    <ul>
      <% @search_results.each do |result| %>
        <li><%= link_to result.name,  product_path(result)%></li>
      <% end %>
      <hr>
    </ul>
  <% else %>
    <p>No results for this query</p>
  <% end %>
<% end %>

<div id="product_list">
  <% if @products.any? %>
    <ul>
      <% @products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
    <%= paginate @products %>
  <% else %>
    <p>There are no products yet.</p>
  <% end %>
</div>

<% if is_admin? %>
  <p><%= link_to "Create new product", new_product_path %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<hr>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.content, product_review_path(@product, review) %>
        <ul>
          <li><%= review.author %></li>
        </ul>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>
<hr>
<br>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<% if is_admin? %>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<% end %>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Review by: <%= @review.author %></h1>
<hr>
<h2>Product: <%= @product.name %></h2><p>reviewed on: <%= @review.created_at %>
<p><em><%= @review.content %></em></p>
<br>
<br>
<hr>
<br>

<% if is_admin? %>
  <p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
  <p><%= link_to "Delete review", product_review_path(@product, @review),
                          :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>
<% end %>

<p><%= link_to "Return to product", product_path(@product) %></p>